#!/usr/bin/env node
// Reads skills/pdf-template-author.md and emits src/embedded-skill.ts as a
// single exported string constant. Run automatically via the `prebuild` hook.
//
// The embedded file is gitignored; each build regenerates it. This keeps the
// markdown file as the single source of truth without requiring runtime
// filesystem access from the published binary.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const skillPath = resolve(repoRoot, "skills/pdf-template-author.md");
const outPath = resolve(repoRoot, "src/embedded-skill.ts");

const skill = readFileSync(skillPath, "utf8");

// JSON.stringify produces a valid TS string literal with all escapes handled.
const body = `// THIS FILE IS GENERATED by scripts/bake-skill.mjs — DO NOT EDIT.
// Regenerated on every build from skills/pdf-template-author.md.

export const SKILL: string = ${JSON.stringify(skill)};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body, "utf8");

console.log(
  `baked skill: ${skill.length} chars → src/embedded-skill.ts`,
);
