import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { randomBytes } from "node:crypto";

/**
 * Waits for a single OAuth-style callback on http://127.0.0.1:<port>/callback.
 * Accepts only the `state` value generated by the caller — anything else is
 * rejected with 400 and does NOT resolve the promise.
 *
 * The server listens on a random port in the loopback range 40000-49999.
 * The range is intentionally narrow so the server side can validate it.
 */
export interface LoopbackResult {
  port: number;
  state: string;
  /** Promise that resolves with the token received from the callback. */
  waitForToken(timeoutMs?: number): Promise<string>;
  /** Force-close the server (idempotent). */
  close(): void;
}

export interface StartLoopbackOptions {
  /** Optional injected state for tests. Otherwise randomly generated. */
  state?: string;
  /** Port range (inclusive) to pick a random port from. Defaults to 40000-49999. */
  portRange?: [number, number];
  /** Maximum attempts to bind a random port before giving up. */
  maxBindAttempts?: number;
}

export async function startLoopbackServer(
  opts: StartLoopbackOptions = {},
): Promise<LoopbackResult> {
  const state = opts.state ?? randomBytes(16).toString("hex");
  const [lo, hi] = opts.portRange ?? [40000, 49999];
  const maxAttempts = opts.maxBindAttempts ?? 10;

  let resolveToken: ((token: string) => void) | undefined;
  let rejectToken: ((err: Error) => void) | undefined;
  const tokenPromise = new Promise<string>((res, rej) => {
    resolveToken = res;
    rejectToken = rej;
  });

  let server: Server | undefined;
  let closed = false;

  const handler = (req: IncomingMessage, res: ServerResponse): void => {
    const url = new URL(req.url ?? "/", "http://127.0.0.1");
    if (url.pathname !== "/callback") {
      res.writeHead(404, { "Content-Type": "text/plain" });
      res.end("not found");
      return;
    }
    const gotState = url.searchParams.get("state");
    const gotToken = url.searchParams.get("token");
    if (gotState !== state || !gotToken) {
      res.writeHead(400, { "Content-Type": "text/plain" });
      res.end("invalid state or missing token");
      return;
    }
    res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
    res.end(SUCCESS_HTML);
    resolveToken?.(gotToken);
  };

  // Try random ports until one binds.
  const port = await new Promise<number>((resolveBind, rejectBind) => {
    let attempts = 0;
    const tryBind = (): void => {
      attempts++;
      if (attempts > maxAttempts) {
        rejectBind(new Error(`failed to bind a loopback port after ${maxAttempts} attempts`));
        return;
      }
      const candidate = randomIntInclusive(lo, hi);
      const s = createServer(handler);
      s.once("error", (err: NodeJS.ErrnoException) => {
        if (err.code === "EADDRINUSE") {
          s.close();
          tryBind();
        } else {
          rejectBind(err);
        }
      });
      s.listen(candidate, "127.0.0.1", () => {
        server = s;
        resolveBind(candidate);
      });
    };
    tryBind();
  });

  const close = (): void => {
    if (closed) return;
    closed = true;
    server?.close();
  };

  const waitForToken = (timeoutMs = 5 * 60 * 1000): Promise<string> => {
    const timeout = setTimeout(() => {
      rejectToken?.(new Error(`timed out after ${Math.round(timeoutMs / 1000)}s waiting for callback`));
      close();
    }, timeoutMs);
    return tokenPromise.finally(() => {
      clearTimeout(timeout);
      close();
    });
  };

  return { port, state, waitForToken, close };
}

function randomIntInclusive(lo: number, hi: number): number {
  return Math.floor(Math.random() * (hi - lo + 1)) + lo;
}

const SUCCESS_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>makesPDF CLI — signed in</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; padding: 40px; max-width: 480px; margin: 0 auto; color: #111; }
  h1 { font-size: 20px; margin-bottom: 8px; }
  p  { color: #555; line-height: 1.5; }
</style></head>
<body>
  <h1>Signed in</h1>
  <p>You can close this tab and return to your terminal.</p>
</body></html>`;
